apiVersion: apps/v1
kind: Deployment
metadata:
  name: sveltekit-app
  labels:
    app: sveltekit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sveltekit
  template:
    metadata:
      labels:
        app: sveltekit
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: sveltekit
        image: docker.io/kennyd3d/demo-sveltekit:0.0.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"