name: Build Docker Container on Windows

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        uses: ./.github/actions/windows-kube-setup
        with:
          kube_b64: ${{ secrets.KUBE_B64 }}
  
      - name: Build Windows Docker Image 
        run: |
          docker build -t demo-sveltekit:0.0.1 -f Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Windows Docker Image
        run: |
          docker build --build-arg ORIGIN=${{ secrets.ORIGIN }} -t ${{ secrets.DOCKER_USER }}/demo-sveltekit:0.0.1 -f Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/demo-sveltekit:0.0.1
          
      - name: Apply Deployment
        run: |
          kubectl apply -f ./CICD/deployment.yaml
