name: Build Docker Container on Windows

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .kube directory
        shell: pwsh
        run: |
          $kubeConfigDir = "$env:USERPROFILE\.kube"
          if (-not (Test-Path $kubeConfigDir)) {
            New-Item -Path $kubeConfigDir -ItemType Directory
          }
          
      - name: Decode and write kubeconfig
        shell: pwsh
        run: |
          $KubeConfig = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.KUBE_B64 }}"))
          Set-Content -Path "$env:USERPROFILE\.kube\config" -Value $KubeConfig
  
      - name: Build Windows Docker Image 
        run: |
          docker build -t demo-sveltekit:0.0.0 -f Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Windows Docker Image
        run: |
          docker build --build-arg ORIGIN=${{ secrets.ORIGIN }} -t ${{ secrets.DOCKER_USER }}/demo-sveltekit:0.0.0 -f Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/demo-sveltekit:0.0.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        id: install

      - name: Apply Deployment
        run: |
          kubectl apply -f ./CICD/deployment.yaml
