name: Build Docker Container on Windows

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Windows Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/demo-sveltekit:0.0.0 -f Dockerfile .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USER }}/demo-sveltekit:0.0.0
